import {
  BrainCircuit,
  Crown,
  Radio,
  Zap,
  Clock,
  Building2,
  Lock,
  Target,
  CheckCircle2,
  Handshake,
  ShoppingCart,
  Smartphone,
  Globe,
  Settings,
  BarChart3,
  Headphones,
  Shield,
  Timer,
  Users,
  ClipboardList,
  Palette,
  Laptop,
  Rocket,
  Smile,
  TrendingUp,
  Factory,
  Hospital,
  CircleDollarSign,
  BookOpen,
  Truck,
  Home,
  Plane,
  Utensils,
  MessageSquare,
  Bot,
  Cloud,
  Building,
  Store,
  Circle,
  CreditCard,
  ShoppingBag,
  Wrench,
  LucideProps
} from "lucide-react";
import React from "react";

export const Icons = {
  Brain: BrainCircuit,
  Crown: Crown,
  Radio: Radio,
  Zap: Zap,
  Clock: Clock,
  Building2: Building2,
  Lock: Lock,
  Target: Target,
  Check: CheckCircle2,
  Handshake: Handshake,
  ShoppingCart: ShoppingCart,
  Smartphone: Smartphone,
  Globe: Globe,
  Settings: Settings,
  BarChart: BarChart3,
  Headphones: Headphones,
  Shield: Shield,
  Timer: Timer,
  Users: Users,
  Clipboard: ClipboardList,
  Palette: Palette,
  Laptop: Laptop,
  Rocket: Rocket,
  Smile: Smile,
  TrendingUp: TrendingUp,
  Factory: Factory,
  Hospital: Hospital,
  CircleDollarSign: CircleDollarSign,
  BookOpen: BookOpen,
  Truck: Truck,
  Home: Home,
  Plane: Plane,
  Utensils: Utensils,
  MessageSquare: MessageSquare,
  Bot: Bot,
  Cloud: Cloud,
  Building: Building,
  Store: Store,
  Circle: Circle,
  CreditCard: CreditCard,
  ShoppingBag: ShoppingBag,
  Wrench: Wrench
};

export type IconType = React.ElementType<LucideProps>;
